In [110]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/kc1-csvsdmlp/kc1_csv.csv
/kaggle/input/cm1naivebayes/CM1.csv


In [111]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.decomposition import PCA as sklearnPCA

# Supress unnecessary warnings so that presentation looks clean
import warnings
warnings.filterwarnings("ignore")

In [112]:
import pandas  as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [113]:
data = pd.read_csv('../input/cm1naivebayes/CM1.csv')
df = pd.DataFrame(data)
data.head(6)

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        6.0           9.0         2.0                   1.0           0.0   
1       15.0           7.0         3.0                   1.0          19.0   
2       27.0           9.0         1.0                   4.0          22.0   
3        7.0           3.0         2.0                   0.0           0.0   
4       51.0          25.0        13.0                   0.0          14.0   
5        3.0           5.0         2.0                   0.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    5.0                 0.2             8.0   
1             12.0                    4.0                 0.1             6.0   
2             16.0                    5.0                 0.2             8.0   
3              4.0                    2.0                 0.2             2.0   
4             48.0                   13.0                 0.1            24.0   
5              8.0                    3.0                 0.2             4.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0               2.0  ...        14.0                              0.2   
1               2.0  ...        15.0                              0.1   
2               2.0  ...        15.0                              0.1   
3               2.0  ...         6.0                              0.1   
4               2.0  ...        85.0                              0.1   
5               2.0  ...        11.0                              0.2   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          19.0           44.0                 15.0                  15.0   
1          51.0           90.0                 32.0                  27.0   
2          37.0           74.0                 33.0                  22.0   
3           9.0           14.0                  7.0                  10.0   
4         192.0          229.0                 71.0                  20.0   
5          15.0           21.0                  5.0                  12.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             32.0               4.0       25.0          N  
1             67.0              39.2       32.0          Y  
2             83.0              47.3       33.0          Y  
3             20.0               0.0       12.0          N  
4            172.0              11.7      106.0          N  
5             19.0               0.0       15.0          N  

[6 rows x 38 columns]

In [114]:
# Assigning X and y values for the dataset
X = df.loc[:,df.columns!='Defective']
X.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        6.0           9.0         2.0                   1.0           0.0   
1       15.0           7.0         3.0                   1.0          19.0   
2       27.0           9.0         1.0                   4.0          22.0   
3        7.0           3.0         2.0                   0.0           0.0   
4       51.0          25.0        13.0                   0.0          14.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    5.0                 0.2             8.0   
1             12.0                    4.0                 0.1             6.0   
2             16.0                    5.0                 0.2             8.0   
3              4.0                    2.0                 0.2             2.0   
4             48.0                   13.0                 0.1            24.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0               2.0  ...                       8.0        14.0   
1               2.0  ...                       6.0        15.0   
2               2.0  ...                       8.0        15.0   
3               2.0  ...                       2.0         6.0   
4               2.0  ...                      24.0        85.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                              0.2          19.0           44.0   
1                              0.1          51.0           90.0   
2                              0.1          37.0           74.0   
3                              0.1           9.0           14.0   
4                              0.1         192.0          229.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 15.0                  15.0             32.0   
1                 32.0                  27.0             67.0   
2                 33.0                  22.0             83.0   
3                  7.0                  10.0             20.0   
4                 71.0                  20.0            172.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0               4.0       25.0  
1              39.2       32.0  
2              47.3       33.0  
3               0.0       12.0  
4              11.7      106.0  

[5 rows x 37 columns]

In [115]:
y = df['Defective']
y.head()

0    N
1    Y
2    Y
3    N
4    N
Name: Defective, dtype: object

In [116]:
# Splitting Train and Test values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [117]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [118]:
# import svc
from sklearn.svm import SVC

# Creating a instance
classifier = SVC(kernel='rbf',random_state=None)

# Fitting the model
classifier.fit(X_train, y_train)

SVC()

In [119]:
classifier.intercept_

array([-0.53336147])

In [120]:
classifier.n_support_

array([57, 26], dtype=int32)

In [121]:
classifier.support_vectors_

array([[-0.10765669,  0.3121548 ,  0.38170012, ...,  0.0279608 ,
        -1.30662215,  0.42257422],
       [-0.10765669, -0.57594014, -0.67126573, ..., -0.24262759,
         1.2873461 , -0.42110269],
       [-0.4056192 ,  2.21521537, -0.40802427, ...,  1.39172631,
         0.06695553,  1.89410372],
       ...,
       [-0.61844956, -0.32219873,  0.38170012, ..., -0.08027456,
        -0.31090599, -0.02869483],
       [-0.49075134, -0.57594014, -0.40802427, ..., -0.51321599,
         1.42010826, -0.61730663],
       [ 1.50985406,  1.45399114,  1.69790743, ...,  1.79219713,
         0.75119125,  1.44283468]])

In [122]:
# Predicting the values
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Confusion matrix
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)

cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)

[[213   1]
 [ 19   7]]
[[86  2]
 [16  0]]


In [124]:
# Accuracy
accuracy_train = accuracy_score(y_train, y_pred_train)
print(accuracy_train)

0.9166666666666666


In [125]:
accuracy_test = accuracy_score(y_test, y_pred_test)
print(accuracy_test)

0.8269230769230769


In [126]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           N       0.84      0.98      0.91        88
           Y       0.00      0.00      0.00        16

    accuracy                           0.83       104
   macro avg       0.42      0.49      0.45       104
weighted avg       0.71      0.83      0.77       104

