In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/kc1-csvsdmlp/kc1_csv.csv


In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.decomposition import PCA as sklearnPCA

# Supress unnecessary warnings so that presentation looks clean
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas  as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [4]:
data = pd.read_csv('../input/kc1-csvsdmlp/kc1_csv.csv')
df = pd.DataFrame(data)
data.head(6)

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  ...  \
0   1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30  ...   
1   1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00  ...   
2  83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61  ...   
3  46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73  ...   
4  25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95  ...   
5  43.0   3.0    1.0    3.0  115.0  569.73  0.09  11.27  50.53   6423.73  ...   

   lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0       2          2        2                  2      1.2        1.2   
1       1          1        1                  1      1.0        1.0   
2      65         10        6                  0     18.0       25.0   
3      37          2        5                  0     16.0       28.0   
4      21          0        2                  0     11.0       10.0   
5      35          2        4                  0     11.0       20.0   

   total_Op  total_Opnd  branchCount  defects  
0       1.2         1.2          1.4    False  
1       1.0         1.0          1.0     True  
2     107.0        64.0         21.0     True  
3      89.0        52.0         15.0     True  
4      41.0        17.0          5.0     True  
5      74.0        41.0          5.0     True  

[6 rows x 22 columns]

In [5]:
# Assigning X and y values for the dataset
X = df.loc[:,df.columns!='defects']
X.head()

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  ...  \
0   1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30  ...   
1   1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00  ...   
2  83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61  ...   
3  46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73  ...   
4  25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95  ...   

         t  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0     1.30       2          2        2                  2      1.2        1.2   
1     1.00       1          1        1                  1      1.0        1.0   
2  1187.70      65         10        6                  0     18.0       25.0   
3   635.37      37          2        5                  0     16.0       28.0   
4   132.33      21          0        2                  0     11.0       10.0   

   total_Op  total_Opnd  branchCount  
0       1.2         1.2          1.4  
1       1.0         1.0          1.0  
2     107.0        64.0         21.0  
3      89.0        52.0         15.0  
4      41.0        17.0          5.0  

[5 rows x 21 columns]

In [6]:
y = df['defects']
y.head()

0    False
1     True
2     True
3     True
4     True
Name: defects, dtype: bool

In [7]:
# Splitting Train and Test values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
# import svc
from sklearn.svm import SVC

# Creating a instance
classifier = SVC(kernel='rbf',random_state=None)

# Fitting the model
classifier.fit(X_train, y_train)

SVC()

In [10]:
classifier.intercept_

array([-0.22196583])

In [11]:
classifier.n_support_

array([255, 223], dtype=int32)

In [12]:
classifier.support_vectors_

array([[-0.08011917,  0.04289403, -0.30806172, ..., -0.23012386,
        -0.36324743, -0.08369994],
       [ 0.97423671,  0.29553408,  0.60830084, ...,  1.45726959,
         1.17140757,  0.67313756],
       [-0.34370814, -0.20974601, -0.30806172, ..., -0.38179968,
        -0.39394053, -0.20983952],
       ...,
       [ 2.52282192,  2.06401441,  2.89920724, ...,  1.79854017,
         2.18427986,  2.06067296],
       [ 0.08462394, -0.46238606, -0.30806172, ...,  0.18698463,
         0.28130767, -0.46211868],
       [ 1.04013395,  1.30609427, -0.30806172, ...,  2.19668919,
         2.49121086,  1.30383547]])

In [13]:
# Predicting the values
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Confusion matrix
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)

cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)

[[1232   12]
 [ 171   61]]
[[527  12]
 [ 79  15]]


In [15]:
# Accuracy
accuracy_train = accuracy_score(y_train, y_pred_train)
print(accuracy_train)

0.8760162601626016


In [16]:
accuracy_test = accuracy_score(y_test, y_pred_test)
print(accuracy_test)

0.8562401263823065


In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

       False       0.87      0.98      0.92       539
        True       0.56      0.16      0.25        94

    accuracy                           0.86       633
   macro avg       0.71      0.57      0.58       633
weighted avg       0.82      0.86      0.82       633

